services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  php-fpm:
    image: php:8.4.7-fpm-alpine
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
